# The URL the site will be built for
base_url = "https://fm.huyixi.com"
title = "散步随想"
author = "huyixi"
compile_sass = true
build_search_index = false
generate_feeds = true
feed_filenames = ["rss.xml"]

[markdown]
highlight_code = false

[extra]
rss = "https://fm.huyixi.com/rss.xml"
slogan = "散步才是正经事儿"
spotify = "https://open.spotify.com/show/your-podcast-id"
google_podcasts = "https://podcasts.google.com/feed/your-podcast-id"
xiaoyuzhou = "https://www.xiaoyuzhoufm.com/podcast/your-podcast-id"
share_link = "https://fm.huyixi.com"
